// Permission Modules
export const permissionModules  = [

    // Admission
    {
        moduleName:'admission',
        subModules:[
            // Global Master
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-session',
                        threads:[
                            'define-academic-year',
                            'define-financial-year'
                        ]
                    },
                    {
                        pageName:'define-remark'
                    },
                    {
                        pageName:'define-tc-details',
                        threads:[
                            'define-tc-caste',
                            'term-master'
                        ]
                    },
                    {
                        pageName:'stationary-details'
                    },
                    {
                        pageName:'define-document-type'
                    },
                    {
                        pageName:'define-stream'
                    },
                    {
                        pageName:'define-subject'
                    },
                    {
                        pageName:'define-optional-subject'
                    },
                    {
                        pageName:'student-health-master',
                        threads:[
                            'health-unit-master',
                            'health-master',
                            'define-term',
                            'student-health-entry'
                        ]
                    },
                    {
                        pageName:'define-blood-group'
                    },
                    {
                        pageName:'define-religion'
                    },
                    {
                        pageName:'define-category'
                    },
                    {
                        pageName:'define-caste'
                    },
                    {
                        pageName:'define-parish'
                    },
                    {
                        pageName:'define-nationality'
                    },
                    {
                        pageName:'define-cadet-type'
                    },
                    {
                        pageName:'define-house'
                    },
                    {
                        pageName:'define-club'
                    },
                    {
                        pageName:'parents-status'
                    },
                    {
                        pageName:'possible-siblings'
                    },
                    {
                        pageName:'import-student'
                    }
                ]
            },
            // Master Settings
            {
                subModuleName:'master-settings',
                pages:[
                    {
                        pageName:'change-academic'
                    },
                    {
                        pageName:'admission-open'
                    },
                    {
                        pageName:'enquiry-no-setting'
                    },
                    {
                        pageName:'admission-setting'
                    },
                    {
                        pageName:'student-class-promotion'
                    },
                    {
                        pageName:'assign-roll-no-to-student'
                    },
                    {
                        pageName:'assign-computer-no-to-student'
                    },
                    {
                        pageName:'update-student-details'
                    },
                    {
                        pageName:'student-image-download'
                    },
                    {
                        pageName:'update-address-and-blood'
                    },
                    {
                        pageName:'admission-form-settings'
                    },
                    {
                        pageName:'report-layout-setting'
                    },
                    {
                        pageName:'session-transfer'
                    }
                ]
            },
            // Admission
            {
                subModuleName:'admission',
                pages:[
                    {
                        pageName:'enquiry'
                    },
                    {
                        pageName:'enquiry-follow-up'
                    },
                    {
                        pageName:'admission-form-registration'
                    },
                    {
                        pageName:'entrance-test',
                        threads:[
                            'define-merit-criteria',
                            'slot-creation',
                            'slot-wise-point-entry',
                            're-sloting',
                            'merit-list-generation',
                            'manual-list-generation',
                        ]
                    },
                    {
                        pageName:'admission'
                    },
                    {
                        pageName:'upload-student-document'
                    },
                    {
                        pageName:'requests-for-changes-from-parents'
                    },
                    {
                        pageName:'admission-entry'
                    },
                    {
                        pageName:'generate-student-info-performa-in-bulk'
                    },
                    {
                        pageName:'create-id-card'
                    },
                    {
                        pageName:'print-student-label'
                    }
                ]
            },
            // Certificate
            {
                subModuleName:'certificate',
                pages:[
                    {
                        pageName:'tc',
                        threads:[
                            'tc-form',
                            'tc-form-class-wise',
                            'generate-tc',
                            'generate-tc-in-bulk',
                            'tc-report',
                        ]
                    },
                    {
                        pageName:'certificates'
                    },
                ]
            },
            // Reports
            {
                subModuleName:'reports',
                pages:[
                    {
                        pageName:'prospectud-charges-report'
                    },
                    {
                        pageName:'merit-list-generation'
                    },
                    {
                        pageName:'merit-criteria-print'
                    },
                    {
                        pageName:'registration-report'
                    },
                    {
                        pageName:'admission-report'
                    },
                    {
                        pageName:'merit-list-report'
                    },
                    {
                        pageName:'admission-collection-report'
                    },
                    {
                        pageName:'slot-report'
                    },
                    {
                        pageName:'search-and-import-online-registration'
                    },
                    {
                        pageName:'sibling-report'
                    },
                    {
                        pageName:'student-house-wise-strength-report'
                    },
                    {
                        pageName:'student-document-details'
                    },
                    {
                        pageName:'class-wise-admission-report'
                    },
                    {
                        pageName:'student-repeater-list'
                    },
                    {
                        pageName:'prospectud-charges-report'
                    },
                    {
                        pageName:'verification-admission-form'
                    },
                    {
                        pageName:'admission-withdrawal-register'
                    },
                    {
                        pageName:'total-collection-report-student-wise'
                    },
                    {
                        pageName:'manual-list-generation-report'
                    }
                ]
            }
        ]
    },


    // Fees
    {
        moduleName:'fees',
        subModules:[
            // Global Masters
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-school',
                        threads:[
                            'define-school-board',
                            'school-global-details'
                        ]
                    },
                    {
                        pageName:'define-session',
                        threads:[
                            'define-academic-year',
                            'define-financial-year'
                        ]
                    },
                    {
                        pageName:'define-class-details',
                        threads:[
                            'define-wing',
                            'define-class',
                            'define-section',
                            'relate-class-section'
                        ]
                    },
                    {
                        pageName:'define-bank'
                    },
                    {
                        pageName:'define-sms-template'
                    }
                ]
            },
            // Master Settings
            {
                subModuleName:'master-settings',
                pages:[
                    {
                        pageName:'change-academic'
                    },
                    {
                        pageName:'global-search-option-settings'
                    },
                    {
                        pageName:'fee-entry-setting'
                    },
                    {
                        pageName:'fee-entry-setting-others'
                    },
                    {
                        pageName:'fee-certificate-setting'
                    },
                    {
                        pageName:'set-due-limit'
                    },
                    {
                        pageName:'fee-opening-balance-setting'
                    },
                    {
                        pageName:'bill-book-setting'
                    },
                    {
                        pageName:'generate-bill-book-details'
                    },
                    {
                        pageName:'bus-id-setting'
                    },
                    {
                        pageName:'online-payment-setting'
                    },
                    {
                        pageName:'update-online-data'
                    },
                    {
                        pageName:'report-layout-setting'
                    },
                    {
                        pageName:'session-transfer'
                    },
                ]
            },
            // Fee Master
            {
                subModuleName:'fee-master',
                pages:[
                    {
                        pageName:'define-fee-master',
                        threads:[
                            'define-fee-installment',
                            'define-fee-head',
                            'define-fee-type',
                            'define-fee-group'
                        ]
                    },
                    {
                        pageName:'assign-fee-group-to-fee-head'
                    },
                    {
                        pageName:'assign-amount-group'
                    },
                    {
                        pageName:'assign-multiple-group-to-student'
                    },
                    {
                        pageName:'define-and-assign-concession',
                        threads:[
                            'define-concession',
                            'define-fee-head-concession',
                            'assign-concession-to-student',
                            'define-concession-type',
                            'assign-concession',
                            'assign-concession-to-sigle-student',
                        ]
                    },
                    {
                        pageName:'student-fee-details'
                    },
                    {
                        pageName:'refund-fee'
                    },
                    {
                        pageName:'assign-opening-balance'
                    },
                    {
                        pageName:'verify-structure'
                    },
                    {
                        pageName:'set-student-status'
                    },
                    {
                        pageName:'late-fee-settings',
                        threads:[
                            'late-fee-setting',
                            'late-fee-setting-head-wise',
                        ]
                    },
                    {
                        pageName:'assign-computer-no-to-student'
                    },
                    {
                        pageName:'assign-roll-no-to-student'
                    },
                    {
                        pageName:'create-students-fee-structure'
                    },
                ]
            },
            // Manage Fee
            {
                subModuleName:'manage-fee',
                pages:[
                    {
                        pageName:'fee-entry'
                    },
                    {
                        pageName:'print-fee-receipt-certificate'
                    },
                    {
                        pageName:'modify-fees-receipt'
                    },
                    {
                        pageName:'cancel-fee-receipt'
                    },
                    {
                        pageName:'delete-fee-receipt'
                    },
                    {
                        pageName:'manual-fees-modification'
                    },
                    {
                        pageName:'refun-head-amount'
                    },
                    {
                        pageName:'fee-cheque-clearing'
                    },
                    {
                        pageName:'fees-upload'
                    },
                    {
                        pageName:'fees-upload-with-deposit-bank'
                    },
                    {
                        pageName:'reconsiliation-fee-receipt'
                    },
                    {
                        pageName:'modify-receipt-date-bank'
                    },
                    {
                        pageName:'multiple-remark'
                    },
                    {
                        pageName:'transfer-concession'
                    },
                    {
                        pageName:'amount-without-structure',
                        threads:[
                            'pay-amount-without-structure',
                            'pay-amount-without-structure-for-staff'
                        ]
                    }
                ]
            },
            // Transport
            {
                subModuleName:'transport',
                pages:[
                    {
                        pageName:'travel-agency-master'
                    },
                    {
                        pageName:'define-vehicle-type'
                    },
                    {
                        pageName:'vehicle-alerts'
                    },
                    {
                        pageName:'define-vehicle-details'
                    },
                    {
                        pageName:'define-vehicle-route'
                    },
                    {
                        pageName:'define-vehicle-route-relation'
                    },
                    {
                        pageName:'define-transport-fare-and-group'
                    },
                    {
                        pageName:'define-transport-medium'
                    },
                    {
                        pageName:'define-route-stop'
                    },
                    {
                        pageName:'assign-transport-to-students'
                    },
                    {
                        pageName:'assign-self-transport-to-students'
                    },
                ]
            },
            // Transaction Report
            {
                subModuleName:'transaction-report',
                pages:[
                    {
                        pageName:'collection-reports',
                        threads:[
                            'daily-fee-collection',
                            'daily-fee-collection-list-with-head-fine-filter',
                            'daily-fee-collection-date-wise-with-remark',
                            'daily-fee-collection-date-wise',
                            'daily-fee-collection-account-wise',
                            'daily-fee-collection-receipt-range',
                            'daily-fee-collection-date-fee-group-wise',
                            'pta-daily-fee-collection-date-fee-group-wise',
                            'day-wise-total-collection',
                            'estimated-collection-report',
                            'fee-head-wise-collection-class-range',
                            'fee-collection-student-class-wise',
                            'fee-collection-with-entry-time-concession',
                            'receipt-wise-daily-collection',
                            'receipt-wise-fee-type-collection',
                            'month-wise-collection-report',
                            'monthly-consolidated-report',
                            'total-collection-report',
                            'yearly-collection-report',
                            'student-type-collection-report',
                        ]
                    },
                    {
                        pageName:'defaulter-reports',
                        threads:[
                            'fee-defaulter-list',
                            'fee-defaulter-installment-wise',
                            'fee-defaulter-list-with-head-fine-filter',
                            'fee-defaulter-report-consolidated',
                            'fee-defaulter-report-with-receiving',
                            'fee-defaulter-slip',
                            'unpaid-student-report',
                            'defaulter-list-install-head-wise',
                            'fee-defaulter-list-boarding-wise',
                        ]
                    },
                    {
                        pageName:'ledger-reports',
                        threads:[
                            'annual-student-ledger-1',
                            'annual-student-ledger-2',
                            'annual-student-ledger-3',
                            'student-ledger-class-wise',
                            'fees-student-ledger',
                            'student-ledger-class-wise-with-rec-data',
                        ]
                    },
                    {
                        pageName:'reconcile-reports',
                        threads:[
                            'reconcile-report',
                            'reconcile-installment-class-wise'
                        ]
                    },
                    {
                        pageName:'concession-reports',
                        threads:[
                            'fees-concession',
                            'fees-concession-and-dues',
                            'fees-concession-and-dues-install-head-wise'
                        ]
                    },
                    {
                        pageName:'cancelled-receipt-reports',
                        threads:[
                            'fees-cheque-bounce-report',
                            'cancelled-fees-receipt-report'
                        ]
                    },
                    {
                        pageName:'amount-without-structure-reports',
                        threads:[
                            'amount-without-structure-report',
                            'amount-without-structure-report-for-staff'
                        ]
                    },
                    {
                        pageName:'cheque-reports',
                        threads:[
                            'cheque-clearing-status-report',
                            'cheque-report-date-wise'
                        ]
                    },
                    {
                        pageName:'student-wise-receipt-report'
                    },
                    {
                        pageName:'uploaded-excel-details'
                    },
                    {
                        pageName:'advance-payment-report'
                    },
                    {
                        pageName:'bad-debts-report'
                    },
                    {
                        pageName:'get-difference-from-bank-account'
                    },
                    {
                        pageName:'student-amount-fee-type-wise'
                    },
                ]
            },
            // Reports
            {
                subModuleName:'reports',
                pages:[
                    {
                        pageName:'student-strength',
                        threads:[
                            'class-wise-student-strength',
                            'student-strength-consolidated',
                            'student-strength-ratio-wise-report',
                            'religion-gender-wise-student-strength',
                            'category-gender-wise-student-strength',
                            'route-wise-student-strength',
                            'ews-class-wise-strength-report',
                            'category-gender-religion-wise-student-strength',
                            'transport-student-strength-report'
                        ]
                    },
                    {
                        pageName:'transport-report',
                        threads:[
                            'transport-detail',
                            'paid-transport',
                            'self-transport-report',
                            'transport-report-class-wise',
                            'assigned-transport-report',
                            'estimated-transport-details',
                            'print-transport-id-card',
                        ]
                    },
                    {
                        pageName:'student-details'
                    },
                    {
                        pageName:'class-wise-student-details'
                    },
                    {
                        pageName:'class-section-transfer-report'
                    },
                    {
                        pageName:'class-wise-sibling'
                    },
                    {
                        pageName:'class-wise-mark-list'
                    },
                    {
                        pageName:'date-wise-admission-report'
                    },
                    {
                        pageName:'student-house-wise-report'
                    },
                    {
                        pageName:'student-register-date-wise-report'
                    },
                    {
                        pageName:'student-health-entry-report'
                    },
                    {
                        pageName:'gender-religion-wise-student-report'
                    },
                    {
                        pageName:'category-wise-student-report'
                    },
                    {
                        pageName:'opening-wise-report'
                    },
                    {
                        pageName:'sms-report'
                    },
                    {
                        pageName:'refund-amount'
                    },
                    {
                        pageName:'surname-wise-student-details'
                    },
                    {
                        pageName:'group-wise-student-details'
                    },
                    {
                        pageName:'active-inactive-student-detail-report'
                    },
                    {
                        pageName:'staff-wise-list-report'
                    },
                    {
                        pageName:'mid-year-student-details'
                    },
                ]
            }
        ]
    },


    // Attendance
    {
        moduleName:'attendance',
        subModules:[
            // Global Masters
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-session',
                        threads:[
                            'define-academic-year',
                            'define-financial-year'
                        ]
                    },
                    {
                        pageName:'define-holiday'
                    },
                    {
                        pageName:'define-leave'
                    },
                    {
                        pageName:'define-shift-master'
                    },
                    {
                        pageName:'attendance-settings'
                    },
                    {
                        pageName:'report-settings'
                    },
                    {
                        pageName:'employee-enrollment'
                    },
                    {
                        pageName:'mark-attendance'
                    }
                ]
            },
            // Master Settings
            {
                subModuleName:'master-settings',
                pages:[
                    {
                        pageName:'change-academic'
                    },
                    {
                        pageName:'report-layout-setting'
                    },
                    {
                        pageName:'session-transfer'
                    },
                ]
            },
            // Attendance
            {
                subModuleName:'attendance',
                pages:[
                    {
                        pageName:'assign-leave-to-staff'
                    },
                    {
                        pageName:'modify-staff-in-bulk'
                    },
                    {
                        pageName:'staff-shift-relation'
                    },
                    {
                        pageName:'auto-process-attendance'
                    },
                    {
                        pageName:'mark-manual-attendance'
                    },
                    {
                        pageName:'upload-attendance'
                    },
                    {
                        pageName:'process-leave-application'
                    },
                    {
                        pageName:'process-leave'
                    },
                    {
                        pageName:'reprocess-attendance'
                    },
                    {
                        pageName:'leave-acceptance-employee-wise'
                    },
                    {
                        pageName:'mark-leave-staff-type-wise'
                    },
                    {
                        pageName:'leave-marking'
                    },
                ]
            },
            // Reports
            {
                subModuleName:'reports',
                pages:[
                    {
                        pageName:'daily-reports',
                        threads:[
                            'late-in-early-out-report',
                            'attendance-consolidated-report',
                            'staff-wise-daily-attendance-report',
                            'absent-missing-attendance-report',
                            'biometrics-attendance-detail-department-wise',
                            'weekly-attendance-report',
                            'daily-performance-report',
                            'attendance-report'
                        ]
                    },
                    {
                        pageName:'monthly-reports',
                        threads:[
                            'attendance-report-monthly-wise',
                            'monthly-attendance-report',
                            'monthly-performance-report',
                            'school-staff-attendance-register',
                            'monthly-late-in-count-report',
                            'monthly-consolidated-biometric-report',
                        ]
                    },
                    {
                        pageName:'leave-reports',
                        threads:[
                            'leave-format-report',
                            'leave-balance-report',
                            'sanctioned-leave-report',
                            'leave-card-report',
                            'leave-ledger-report',
                            'leave-register-report',
                            'leave-bucket-report'
                        ]
                    },
                    {
                        pageName:'other-reports',
                        threads:[
                            'staff-shift-relation-report',
                            'attendance-analysis-report',
                            'lwp-year-wise-report',
                        ]
                    }
                ]
            }
        ]
    },


    // Payroll
    {
        moduleName:'payroll',
        subModules:[
            // Global Masters
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-session',
                        threads:[
                            'define-academic-year',
                            'define-financial-year'
                        ]
                    },
                    {
                        pageName:'define-department'
                    },
                    {
                        pageName:'define-profession'
                    },
                    {
                        pageName:'define-designation'
                    },
                    {
                        pageName:'define-staff-type'
                    },
                    {
                        pageName:'define-document-type'
                    },
                    {
                        pageName:'human-resources',
                        threads:[
                            'admission-settings',
                            'current-job-opening',
                            'admission-open',
                            'candidate-registration',
                            'shortlisted-candidate',
                            'employee-registration',
                            'update-staff-profile',
                            'rejoin-staff',
                            'define-reminder',
                            'report-settings',
                            'assign-transport-to-staff'
                        ]
                    }
                ]
            },
            // Master Settings
            {
                subModuleName:'master-settings',
                pages:[
                    {
                        pageName:'define-global-settings'
                    },
                    {
                        pageName:'change-academic'
                    },
                    {
                        pageName:'report-layout-setting'
                    },
                    {
                        pageName:'session-transfer'
                    }
                ]
            },
            // Payroll Master
            {
                subModuleName:'payroll-master',
                pages:[
                    {
                        pageName:'create-salary-structure',
                        threads:[
                            'define-salary-head',
                            'relate-static-dynamic-heads',
                            'define-salary-group',
                            'assign-salary-head-to-group',
                            'assign-salary-group-to-staff',
                            'bulk-salary-head-assign',
                            'bulk-salary-head-entry',
                            'bulk-head-remark-entry',
                        ]
                    },
                    {
                        pageName:'tds-configuration',
                        threads:[
                            'define-income-tax-slab',
                            'define-id-head-groups',
                            'define-id-head',
                            'define-tds-deductee'
                        ]
                    },
                    {
                        pageName:'pay-scale-configuration',
                        threads:[
                            'define-pay-scale',
                            'define-pay-scale-amount',
                            'define-grade-pay',
                            'define-fixation',
                            'assign-pay-scale-to-staff'
                        ]
                    },
                    {
                        pageName:'generate-barcode'
                    },
                    {
                        pageName:'insurance',
                        threads:[
                            'insurance-vender',
                            'relate-policy-with-employee',
                            'related-policies-with-month',
                        ]
                    },
                    {
                        pageName:'define-salary-account'
                    },
                    {
                        pageName:'define-salary-month'
                    },
                    {
                        pageName:'assign-info-bulk'
                    }
                ]
            },
            // Advance
            {
                subModuleName:'advance',
                pages:[
                    {
                        pageName:'advance-report',
                        threads:[
                            'advance-entry-report',
                            'advance-repayment-report',
                            'advance-ledger-report'
                        ]
                    },
                    {
                        pageName:'fix-advance-a-c'
                    },
                    {
                        pageName:'advance-entry'
                    },
                    {
                        pageName:'advance-repayment'
                    },
                ]
            },
            // Salary Structure
            {
                subModuleName:'salary-structure',
                pages:[
                    {
                        pageName:'increment',
                        threads:[
                            'auto-increment',
                            'increment-rollback',
                        ]
                    },
                    {
                        pageName:'leave-lwp-manual'
                    },
                    {
                        pageName:'occasional-allowance-deduction'
                    },
                    {
                        pageName:'salary-generation'
                    },
                    {
                        pageName:'bank-statement'
                    },
                    {
                        pageName:'insurance-statement'
                    },
                    {
                        pageName:'due-statement'
                    },
                    {
                        pageName:'it-head-entry'
                    },
                    {
                        pageName:'tds-entry'
                    },
                    {
                        pageName:'daily-wages-attendance'
                    },
                    {
                        pageName:'gratuity-calculations'
                    },
                    {
                        pageName:'bonus-calculations'
                    },
                    {
                        pageName:'staff-salary-structure'
                    },
                    {
                        pageName:'generate-salary-status'
                    }
                ]
            },
            // Salary Reports
            {
                subModuleName:'salary-reports',
                pages:[
                    {
                        pageName:'income-tax',
                        threads:[
                            'tds-entry-report',
                            'quarterly-form-24q',
                            'tds-24q',
                            'gross-form-16',
                            'form-16'
                        ]
                    },
                    {
                        pageName:'monthly-reports',
                        threads:[
                            'department-wise-report',
                            'consolidated-salary-statment',
                            'gross-salary-report',
                            'month-wise-salary-report',
                            'monthly-summary-report',
                            'head-wise-gross-salary-report',
                            'staff-statement'
                        ]
                    },
                    {
                        pageName:'yearly-reports',
                        threads:[
                            'reconciliation-report',
                            'annual-salary-paid-report',
                            'salary-statement-employee-wise',
                            'salary-statement-report'
                        ]
                    },
                    {
                        pageName:'bank-statement-report'
                    },
                    {
                        pageName:'salary-sheet'
                    },
                    {
                        pageName:'salary-slip'
                    },
                    {
                        pageName:'insurance-statement-report'
                    },
                    {
                        pageName:'employee-type-wise-report'
                    },
                    {
                        pageName:'estimated-salary-report'
                    },
                ]
            },
            // Reports
            {
                subModuleName:'reports',
                pages:[
                    {
                        pageName:'employee-statistics'
                    },
                    {
                        pageName:'esi-report'
                    },
                    {
                        pageName:'pf-report'
                    },
                    {
                        pageName:'pf-challan-report'
                    },
                    {
                        pageName:'increment-report'
                    },
                    {
                        pageName:'gsli-report'
                    },
                    {
                        pageName:'gratuity-report'
                    },
                    {
                        pageName:'salary-compare'
                    },
                    {
                        pageName:'professional-tax'
                    },
                    {
                        pageName:'super-annuciation-report'
                    },
                    {
                        pageName:'macp-list'
                    },
                    {
                        pageName:'fixation-report'
                    },
                    {
                        pageName:'date-range-retirement-report'
                    },
                    {
                        pageName:'retirement-report'
                    },
                    {
                        pageName:'pension-list'
                    },
                    {
                        pageName:'experience-certificate-report'
                    },
                    {
                        pageName:'comparison-report'
                    },
                    {
                        pageName:'employee-bio-data'
                    }
                ]
            }
        ]
    },


    // Marks Entry
    {
        moduleName:'marks-entry',
        subModules:[]
    },


    // Examinations
    {
        moduleName:'examinations',
        subModules:[]
    },


    // Time Table
    {
        moduleName:'time-table',
        subModules:[
            // Global Masters
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-session',
                        threads:[
                            'define-academic-year',
                            'define-financial-year'
                        ]
                    },
                ]
            },
            // Master Settings
            {
                subModuleName:'master-settings',
                pages:[
                    {
                        pageName:'change-academic'
                    },
                    {
                        pageName:'report-layout-setting'
                    },
                    {
                        pageName:'session-transfer'
                    },
                ]
            },
            // Relation Master
            {
                subModuleName:'relation-master',
                pages:[
                    {
                        pageName:'timetable-global-setting'
                    },
                    {
                        pageName:'teacher-setting'
                    },
                    {
                        pageName:'class-setting'
                    },
                    {
                        pageName:'define-subject'
                    },
                    {
                        pageName:'assign-subject-to-class'
                    },
                    {
                        pageName:'period-allotment'
                    },
                    {
                        pageName:'define-resource'
                    },
                    {
                        pageName:'relate-resource-to-subject'
                    },
                    {
                        pageName:'class-teacher-subject'
                    },
                    {
                        pageName:'define-class-teacher'
                    },
                    {
                        pageName:'period-time-setting'
                    },
                ]
            },
            // Constraints Master
            {
                subModuleName:'constraints-master',
                pages:[
                    {
                        pageName:'parallel-allocation'
                    },
                    {
                        pageName:'fixed-allocation'
                    },
                    {
                        pageName:'consecutive-allocation'
                    },
                    {
                        pageName:'preference-allocation'
                    }
                ]
            },
            // Create Timetable
            {
                subModuleName:'create-timetable',
                pages:[
                    {
                        pageName:'auto-generate-timetable'
                    },
                    {
                        pageName:'view-and-modify-timetable'
                    },
                    {
                        pageName:'replace-teacher'
                    },
                    {
                        pageName:'assign-one-teacher-timetable-to-another'
                    },
                    {
                        pageName:'modify-timetable'
                    }
                ]
            },
            // Substitution Master
            {
                subModuleName:'substitution-master',
                pages:[
                    {
                        pageName:'mark-attendance'
                    },
                    {
                        pageName:'substitution'
                    }
                ]
            },
            // Reports
            {
                subModuleName:'reports',
                pages:[
                    {
                        pageName:'class-timetable-details'
                    },
                    {
                        pageName:'teacher-timetable-details'
                    },
                    {
                        pageName:'subject-details'
                    },
                    {
                        pageName:'class-teacher-details'
                    },
                    {
                        pageName:'master-requirement'
                    },
                    {
                        pageName:'parallel-allocation-details'
                    },
                    {
                        pageName:'subject-wise-teacher-details'
                    },
                    {
                        pageName:'wing-wise-teacher-details'
                    },
                    {
                        pageName:'consecutive-allocation-details'
                    },
                    {
                        pageName:'class-and-resource-details'
                    },
                    {
                        pageName:'week-wise-free-teacher-details'
                    },
                    {
                        pageName:'class-timetable-details'
                    },
                    {
                        pageName:'unallocated-period-details'
                    },
                    {
                        pageName:'day-wise-free-teacher-details'
                    },
                    {
                        pageName:'class-and-subject-taught'
                    },
                    {
                        pageName:'teachers-work-load-details'
                    },
                    {
                        pageName:'day-wise-free-teacher-details'
                    },
                    {
                        pageName:'resource-timetable-details'
                    },
                    {
                        pageName:'particular-class-timetable-details'
                    },
                    {
                        pageName:'class-wise-teacher-allocation-details'
                    },
                    {
                        pageName:'date-wise-substitution-details'
                    },
                    {
                        pageName:'assignment-status'
                    },
                    {
                        pageName:'subject-summary'
                    },
                    {
                        pageName:'subject-wise-teacher-allocation-details'
                    },
                    {
                        pageName:'show-timetable-at-glance'
                    }
                ]
            }
        ]
    },


    // Accounts
    {
        moduleName:'accounts',
        subModules:[
            // Global Masters
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-session',
                        threads:[
                            'define-academic-year',
                            'define-financial-year'
                        ]
                    },
                    {
                        pageName:'define-narration-master'
                    }
                ]
            },
            // Master settings
            {
                subModuleName:'master-settings',
                pages:[
                    {
                        pageName:'change-academic'
                    },
                    {
                        pageName:'account-master-setting'
                    },
                    {
                        pageName:'account-petty-cash-setting'
                    },
                    {
                        pageName:'voucher-print-settings'
                    },
                    {
                        pageName:'voucher-code-settings'
                    },
                    {
                        pageName:'cheque-print-format-setting'
                    },
                    {
                        pageName:'report-layout-setting'
                    },
                    {
                        pageName:'session-transfer'
                    }
                ]
            },
            // Accounts
            {
                subModuleName:'accounts',
                pages:[
                    {
                        pageName:'define-account-group'
                    },
                    {
                        pageName:'define-bank-ledger'
                    },
                    {
                        pageName:'define-party-ledger'
                    },
                    {
                        pageName:'define-general-ledger'
                    },
                    {
                        pageName:'bank-payment-voucher'
                    },
                    {
                        pageName:'cash-payment-voucher'
                    },
                    {
                        pageName:'bank-receipt-voucher'
                    },
                    {
                        pageName:'cash-receipt-voucher'
                    },
                    {
                        pageName:'define-group-nature'
                    },
                    {
                        pageName:'contra-voucher'
                    },
                    {
                        pageName:'journal-voucher'
                    },
                    {
                        pageName:'payment-voucher'
                    },
                    {
                        pageName:'salary-payment-voucher'
                    },
                    {
                        pageName:'cheque-clearing'
                    },
                    {
                        pageName:'cheque-printing'
                    },
                    {
                        pageName:'voucher-image-upload'
                    }
                ]
            },
            // Reports
            {
                subModuleName:'reports',
                pages:[
                    {
                        pageName:'ledger-report',
                        threads:[
                            'ledger-report',
                            'ledger-report-detail',
                            'ledger-report-detail-new',
                            'ledger-report-with-filter'
                        ]
                    },
                    {
                        pageName:'daily-cash-status'
                    },
                    {
                        pageName:'bank-ledger'
                    },
                    {
                        pageName:'cash-bank-book'
                    },
                    {
                        pageName:'day-book'
                    },
                    {
                        pageName:'trial-balance-new'
                    },
                    {
                        pageName:'trial-balance'
                    },
                    {
                        pageName:'profit-loss'
                    },
                    {
                        pageName:'income-expenditure'
                    },
                    {
                        pageName:'balance-sheet'
                    },
                    {
                        pageName:'reconciliation-statment'
                    },
                    {
                        pageName:'journal-ledger-book'
                    },
                    {
                        pageName:'group-wise-report'
                    },
                    {
                        pageName:'fee-account-mismatch'
                    },
                    {
                        pageName:'entry-type-wise-report'
                    },
                    {
                        pageName:'fee-outstandig-report'
                    },
                    {
                        pageName:'depreciation-chart'
                    },
                    {
                        pageName:'depreciation-detail-item-wise'
                    },
                    {
                        pageName:'serialize-voucher-code'
                    }
                ]
            },
        ]
    },


    // Stocks
    {
        moduleName:'stocks',
        subModules:[
            // Global Masters
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-session',
                        threads:[
                            'define-financial-year',
                            'define-academic-year',
                        ]
                    },
                    {
                        pageName:'define-item-category'
                    },
                    {
                        pageName:'define-items-sub-category'
                    },
                    {
                        pageName:'define-unit'
                    },
                    {
                        pageName:'define-item'
                    },
                    {
                        pageName:'define-brand-name'
                    },
                    {
                        pageName:'define-gst-slab'
                    },
                    {
                        pageName:'relate-item-with-gst-slab'
                    }
                ]
            },
            // Master Settings
            {
                subModuleName:'master-settings',
                pages:[
                    {
                        pageName:'change-academic'
                    },
                    {
                        pageName:'stock-master-setting'
                    },
                    {
                        pageName:'notification-scheduler'
                    },
                    {
                        pageName:'set-stock-reminder-details'
                    },
                    {
                        pageName:'report-layout-setting'
                    },
                    {
                        pageName:'session-transfer'
                    }
                ]
            },
            // Stock
            {
                subModuleName:'stock',
                pages:[
                    {
                        pageName:'asset-opening-entry'
                    },
                    {
                        pageName:'opening-qty'
                    },
                    {
                        pageName:'requisition-order'
                    },
                    {
                        pageName:'purchase-order'
                    },
                    {
                        pageName:'purchase-return-entry'
                    },
                    {
                        pageName:'stock-in-entry'
                    },
                    {
                        pageName:'stock-bill-entry'
                    },
                    {
                        pageName:'stock-issue'
                    },
                    {
                        pageName:'multiple-stock-issue'
                    },
                    {
                        pageName:'stock-return'
                    },
                    {
                        pageName:'stock-return-item-wise'
                    },
                    {
                        pageName:'stock-destroy'
                    }
                ]
            },
            // Reports
            {
                subModuleName:'reports',
                pages:[
                    {
                        pageName:'stock-opening-report'
                    },
                    {
                        pageName:'purchase-order-report'
                    },
                    {
                        pageName:'stock-in-report'
                    },
                    {
                        pageName:'bill-report'
                    },
                    {
                        pageName:'employee-issue-report'
                    },
                    {
                        pageName:'employee-return-report'
                    },
                    {
                        pageName:'stock-issue-report'
                    },
                    {
                        pageName:'other-return-report'
                    },
                    {
                        pageName:'stock-ledger'
                    },
                    {
                        pageName:'cumulative-stock-statement-value-wise'
                    },
                    {
                        pageName:'active-stock'
                    },
                    {
                        pageName:'max-stock-report'
                    },
                    {
                        pageName:'min-stock-report'
                    },
                    {
                        pageName:'challan-report'
                    },
                    {
                        pageName:'item-master-report'
                    },
                    {
                        pageName:'purchase-return-report'
                    },
                    {
                        pageName:'stock-destroy-report'
                    }
                ]
            }
        ]
    },


    // Library
    {
        moduleName:'library',
        subModules:[]
    },


    // Users
    {
        moduleName:'users',
        subModules:[
            // Global Master
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-session',
                        threads:[
                            'define-academic-year',
                            'define-financial-year'
                        ]
                    }
                ]
            },
            // Master Settings
            {
                subModuleName:'master-settings',
                pages:[
                    {
                        pageName:'change-academic'
                    },
                    {
                        pageName:'report-layout-setting'
                    },
                    {
                        pageName:'session-transfer'
                    }
                ]
            },
            // Manage Users
            {
                subModuleName:'manage-users',
                pages:[
                    {
                        pageName:'create-user'
                    },
                    {
                        pageName:'fee-type-assign-to-user'
                    },
                    {
                        pageName:'user-permission'
                    },
                    {
                        pageName:'create-role'
                    },
                    {
                        pageName:'user-role'
                    }
                ]
            },
            // Reports
            {
                subModuleName:'reports',
                pages:[]
            }
        ]
    },


    // Qodum Care
    {
        moduleName:'qodum-care',
        subModules:[
            // Global Master
            {
                subModuleName:'global-masters',
                pages:[
                    {
                        pageName:'define-session',
                        threads:[
                            'define-academic-year',
                            'define-financial-year'
                        ]
                    },
                    {
                        pageName:'app-control'
                    }
                ]
            },
        ]
    }

];